baseURL = 'https://example.org/'
languageCode = 'en-us'
disableHugoGeneratorInject = true
title = 'SMASH 2025: The Symposium on Model Accountability, Sustainability and Healthcare'
[params]
shorttitle =  'SMASH 2025'
description = 'The goal of this event is to identify challenges and propose technical, ethical and regulatory solutions to AI safety, data privacy, model interoperability and accountability.'
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = 'Schedule'
    url = '/schedule'
    pageRef = '/schedule'
    weight = 20
  [[menu.main]]
    name = 'Notable papers'
    url = '/notablepapers'
    pageRef = '/notablepapers'
    weight = 30
  [[menu.main]]
    name = 'Code of conduct'
    url = '/condeofconduct'
    pageRef = '/condeofconduct'
    weight = 40