baseURL = 'https://smash.org/'
languageCode = 'en-us'
disableHugoGeneratorInject = true
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    title = 'SMASH 2025: The Symposium on Model Accountability, Sustainability and Healthcare'
    weight = 1
  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'Français'
    title = 'SMASH 2025: Symposium sur  Responsabilité des Modèles, la Durabilité et la Santé'
    weight = 2
[markup.goldmark.renderer]
unsafe= true
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
[languages.en.menus]
  [[languages.en.menus.main]]
    name = 'Call for Papers'
    url = '/callforpapers'
    pageRef = '/callforpapers'
    weight = 15
  [[languages.en.menus.main]]
    name = 'Register'
    url = '/register'
    pageRef = '/register'
    weight = 17
  [[languages.en.menus.main]]
    name = 'Notable Papers'
    url = '/notablepapers'
    pageRef = '/notablepapers'
    weight = 30
  [[languages.en.menus.main]]
    name = 'Organizing Team'
    url = '/organizingteam'
    pageRef = '/organizingteam'
    weight = 40
[languages.fr.menus]
  [[languages.fr.menus.main]]
    name = 'Appel de contributions'
    url = '/callforpapers'
    pageRef = '/callforpapers'
    weight = 15
  [[languages.fr.menus.main]]
    name = "S'inscrire"
    url = '/register'
    pageRef = '/register'
    weight = 17
  [[languages.fr.menus.main]]
    name = 'Articles marquants'
    url = '/notablepapers'
    pageRef = '/notablepapers'
    weight = 30
  [[languages.fr.menus.main]]
    name = 'Équipe organisatrice'
    url = '/organizingteam'
    pageRef = '/organizingteam'
    weight = 40
