[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.147.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.147.2"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.147.2"

[[redirects]]
  from = '/callforpapers'
  to = '/en/callforpapers'
[[redirects]]
  from = '/register'
  to = '/en/register'
[[redirects]]
  from = '/notablepapers'
  to = '/en/notablepapers'
[[redirects]]
  from = '/organizingteam'
  to = '/en/organizingteam'
